name: 3101_proj
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - setuptools=57.4.0
  - ipython
  - pip
  - pip:
    - aiohttp==3.10.8
    - pandas==2.2.3
    - requests==2.32.3 
    - nltk==3.9.1 
    - pyyaml==6.0.2
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pydantic-settings==2.5.2
    - typing_extensions==4.11.0
    - urllib3==2.2.3
    - python-dotenv==1.0.1
    - openai==1.51.0
    - langchain==0.3.1
    - langchain-community==0.3.1
    - langchain-core==0.3.6
    - langchain-openai==0.2.0
    - langchain-text-splitters==0.3.0
    - pillow==10.4.0
    - seaborn==0.13.2
    - plotly==5.24.1
    - bertopic==0.16.3
    - beautifulsoup4==4.12.3
    - matplotlib==3.9.2
    - pio==0.0.3 
    - scikit-learn==1.5.2
    - scipy==1.13.1
    - tqdm==4.66.5
    - torch==2.4.1
    - ipywidgets
    - kagglehub
    - openssl
    - torch 
    - transformers
    - numpy
    - scikit-learn
    - selenium
    